---
# tasks file for ansible-role-wordpress_hosted

- name: Download latest WordPress
  get_url:
    url: "{{ wordpress_hosted_download_url }}{{wordpress_hosted_download_filename }}"
    mode: 0640
    dest: "{{ wordpress_hosted_root_dir }}"
  register: __register_get_url_wordpress

- name: Ensure wordpress_hosted_document_root exists
  file:
    state: directory
    path: "{{ wordpress_hosted_document_root }}"
    mode: 0755

- name: Ensure wordpress_hosted_app_root exists
  file:
    state: directory
    path: "{{ wordpress_hosted_app_root }}"
    mode: 0755

- name: Extract WordPress with unarchive
  unarchive:
    dest: "{{ wordpress_hosted_app_root }}"
    src: "{{ __register_get_url_wordpress.dest }}"
    creates: "{{ wordpress_hosted_app_root }}/wp-config-sample.php"
    extra_opts:
      - --transform
      - s/^wordpress//
  when:
    - ansible_os_family != 'FreeBSD'

- name: Extract WordPress with BSD tar
  shell: "tar -zxf {{ __register_get_url_wordpress.dest }} -C {{ wordpress_hosted_app_root }} -s '/^wordpress//'"
  args:
    creates: "{{ wordpress_hosted_app_root }}/wp-config-sample.php"
  when:
    - ansible_os_family == 'FreeBSD'

- name: Install plugins
  include_tasks: plugins.yml

- name: Create wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_hosted_app_root }}/wp-config.php"
    mode: "{{ wordpress_hosted_wp_config_filemode }}"
    #validate: php -l %s
