---
# tasks file for ansible-role-wordpress_hosted

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ wordpress_hosted_log_dir }}"
    mode: 0755
    owner: "{{ wordpress_hosted_user }}"
    group: "{{ wordpress_hosted_group }}"
    state: directory
  notify: Restart wordpress_hosted

- name: Create db directory
  file:
    path: "{{ wordpress_hosted_db_dir }}"
    mode: 0755
    owner: "{{ wordpress_hosted_user }}"
    group: "{{ wordpress_hosted_group }}"
    state: directory
  notify: Restart wordpress_hosted

- name: Create wordpress_hosted.conf
  template:
    src: wordpress_hosted.conf.j2
    dest: "{{ wordpress_hosted_conf_file }}"
    validate: echo %s
  notify: Restart wordpress_hosted

- name: Start wordpress_hosted
  service:
    name: "{{ wordpress_hosted_service }}"
    enabled: true
    state: started
