---
# tasks file for ansible-role-wordpress_hosted

- name: Ensure wordpress_hosted_distfiles_dir exists
  file:
    state: directory
    path: "{{ wordpress_hosted_distfiles_dir }}"
    mode: 0755

- name: Download latest WordPress
  get_url:
    url: "{{ wordpress_hosted_download_url }}{{wordpress_hosted_download_filename }}"
    mode: 0640
    dest: "{{ wordpress_hosted_distfiles_dir }}"
  register: __register_get_url_wordpress

- name: Ensure wordpress_hosted_document_root exists
  file:
    state: directory
    path: "{{ wordpress_hosted_document_root }}"
    mode: 0755

- name: Ensure wordpress_hosted_app_root exists
  file:
    state: directory
    path: "{{ wordpress_hosted_app_root }}"
    mode: 0755

- name: Extract WordPress with unarchive
  unarchive:
    dest: "{{ wordpress_hosted_app_root }}"
    src: "{{ __register_get_url_wordpress.dest }}"
    creates: "{{ wordpress_hosted_app_root }}/wp-config-sample.php"
    extra_opts:
      - --transform
      - s/^wordpress//

- name: Include wp_salts.yml
  include_tasks: wp_salts.yml

- name: Install plugins
  include_tasks: plugins.yml

- name: Create wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_hosted_app_root }}/wp-config.php"
    mode: "{{ wordpress_hosted_wp_config_filemode }}"
    #validate: php -l %s
